/**
 * Vidéos de démonstration par exercice (clips courts, générés puis
 * recadrés/compressés côté build) — indexées par slug, ajoutées au fur et
 * à mesure. Un exercice sans entrée ici retombe sur l'emoji dans
 * ActiveExerciseScreen (SessionPlayer.tsx), jamais d'écran cassé.
 *
 * Généré automatiquement par scripts/videos/wire-videos.mjs à partir du
 * contenu de public/exercises/ — ne pas éditer à la main, relancer le
 * workflow "Vidéos d'exercices" à la place.
 */
export const EXERCISE_VIDEO: Partial<Record<string, string>> = {
  "auto-massage-quadriceps": "/exercises/auto-massage-quadriceps.mp4",
  "automassage-mollets": "/exercises/automassage-mollets.mp4",
  "blocage-sol-parade-basse": "/exercises/blocage-sol-parade-basse.mp4",
  "bondissements-avant-reception": "/exercises/bondissements-avant-reception.mp4",
  "bondissements-lateraux": "/exercises/bondissements-lateraux.mp4",
  "centre-frappe-couloir": "/exercises/centre-frappe-couloir.mp4",
  "changement-direction-reactif-partenaire": "/exercises/changement-direction-reactif-partenaire.mp4",
  "circuit-ballon-cardio-technique": "/exercises/circuit-ballon-cardio-technique.mp4",
  "circuit-cardio-combine": "/exercises/circuit-cardio-combine.mp4",
  "conduite-balle-int-ext": "/exercises/conduite-balle-int-ext.mp4",
  "controle-orientation-corps": "/exercises/controle-orientation-corps.mp4",
  "controle-oriente-frappe-rapide": "/exercises/controle-oriente-frappe-rapide.mp4",
  "course-cote-courte": "/exercises/course-cote-courte.mp4",
  "course-lente-relachement": "/exercises/course-lente-relachement.mp4",
  "crochet-interieur-frappe": "/exercises/crochet-interieur-frappe.mp4",
  "debordement-exterieur-centre": "/exercises/debordement-exterieur-centre.mp4",
  "defense-1v1-face-dribbleur": "/exercises/defense-1v1-face-dribbleur.mp4",
  "departs-reactifs-signal": "/exercises/departs-reactifs-signal.mp4",
  "distribution-precise-main": "/exercises/distribution-precise-main.mp4",
  "distribution-sous-pression": "/exercises/distribution-sous-pression.mp4",
  "dribble-1v1-plot-mobile": "/exercises/dribble-1v1-plot-mobile.mp4",
  "duel-aerien-defensif": "/exercises/duel-aerien-defensif.mp4",
  "duel-face-a-face-gardien": "/exercises/duel-face-a-face-gardien.mp4",
  "echelle-agilite-pieds": "/exercises/echelle-agilite-pieds.mp4",
  "elastique-marche-laterale": "/exercises/elastique-marche-laterale.mp4",
  "enchainement-plongeon-releve-plongeon": "/exercises/enchainement-plongeon-releve-plongeon.mp4",
  "equilibre-unipodal-genoux": "/exercises/equilibre-unipodal-genoux.mp4",
  "etirement-fessiers-pigeon": "/exercises/etirement-fessiers-pigeon.mp4",
  "etirements-adducteurs": "/exercises/etirements-adducteurs.mp4",
  "etirements-ischio-dynamiques": "/exercises/etirements-ischio-dynamiques.mp4",
  "feintes-corps-piquet": "/exercises/feintes-corps-piquet.mp4",
  "fentes-avant-alternees": "/exercises/fentes-avant-alternees.mp4",
  "fentes-laterales-mobilite-hanches": "/exercises/fentes-laterales-mobilite-hanches.mp4",
  "finition-1v1-gardien": "/exercises/finition-1v1-gardien.mp4",
  "footing-continu": "/exercises/footing-continu.mp4",
  "footing-tempo-progressif": "/exercises/footing-tempo-progressif.mp4",
  "footwork-echelle-gardien": "/exercises/footwork-echelle-gardien.mp4",
  "fractionne-30-30": "/exercises/fractionne-30-30.mp4",
  "frappe-basse-enroulee-poteau": "/exercises/frappe-basse-enroulee-poteau.mp4",
  "frappe-enroulee-cible": "/exercises/frappe-enroulee-cible.mp4",
  "frappe-exterieur-surprise": "/exercises/frappe-exterieur-surprise.mp4",
  "frappe-longue-distance": "/exercises/frappe-longue-distance.mp4",
  "frappe-pied-faible-cible": "/exercises/frappe-pied-faible-cible.mp4",
  "frappe-premiere-intention": "/exercises/frappe-premiere-intention.mp4",
  "frappe-puissance-surface": "/exercises/frappe-puissance-surface.mp4",
  "frappe-volee-ballon-lance": "/exercises/frappe-volee-ballon-lance.mp4",
  "gainage-lateral": "/exercises/gainage-lateral.mp4",
  "gainage-lombaire-doux": "/exercises/gainage-lombaire-doux.mp4",
  "gainage-mountain-climbers": "/exercises/gainage-mountain-climbers.mp4",
  "gainage-oiseau-chien-stabilite": "/exercises/gainage-oiseau-chien-stabilite.mp4",
  "gainage-planche-ventrale": "/exercises/gainage-planche-ventrale.mp4",
  "gainage-rotation-medecine": "/exercises/gainage-rotation-medecine.mp4",
  "gammes-cardio-ballon": "/exercises/gammes-cardio-ballon.mp4",
  "hiit-leger-20-10": "/exercises/hiit-leger-20-10.mp4",
  "hip-thrust-sol": "/exercises/hip-thrust-sol.mp4",
  "interception-lecture-trajectoire": "/exercises/interception-lecture-trajectoire.mp4",
  "jockey-defensif-pas-chasses": "/exercises/jockey-defensif-pas-chasses.mp4",
  "jonglage-cardio-deplacement": "/exercises/jonglage-cardio-deplacement.mp4",
  "jonglages-progressifs": "/exercises/jonglages-progressifs.mp4",
  "marche-active-accelerations": "/exercises/marche-active-accelerations.mp4",
  "mobilite-chevilles": "/exercises/mobilite-chevilles.mp4",
  "mobilite-epaules-cercles": "/exercises/mobilite-epaules-cercles.mp4",
  "mobilite-hanches-cercles": "/exercises/mobilite-hanches-cercles.mp4",
  "montees-marche-explosives": "/exercises/montees-marche-explosives.mp4",
  "navette-progressive": "/exercises/navette-progressive.mp4",
  "nordic-curl-assiste": "/exercises/nordic-curl-assiste.mp4",
  "passe-cassee-entre-lignes": "/exercises/passe-cassee-entre-lignes.mp4",
  "passe-exterieur-tranchante": "/exercises/passe-exterieur-tranchante.mp4",
  "passe-longue-diagonale": "/exercises/passe-longue-diagonale.mp4",
  "passes-courtes-triangle": "/exercises/passes-courtes-triangle.mp4",
  "passes-mur-controle": "/exercises/passes-mur-controle.mp4",
  "plongeon-lateral-amorti": "/exercises/plongeon-lateral-amorti.mp4",
  "pompes-genoux-pieds": "/exercises/pompes-genoux-pieds.mp4",
  "prise-balle-haute": "/exercises/prise-balle-haute.mp4",
  "proprioception-cheville-serviette": "/exercises/proprioception-cheville-serviette.mp4",
  "protection-ballon-dos-adversaire": "/exercises/protection-ballon-dos-adversaire.mp4",
  "reduction-angle-1v1": "/exercises/reduction-angle-1v1.mp4",
  "reflexes-frappes-rapprochees": "/exercises/reflexes-frappes-rapprochees.mp4",
  "reflexes-mains-rapprochees": "/exercises/reflexes-mains-rapprochees.mp4",
  "relance-pied-courte-longue": "/exercises/relance-pied-courte-longue.mp4",
  "remise-une-touche": "/exercises/remise-une-touche.mp4",
  "renforcement-mollets-pointes": "/exercises/renforcement-mollets-pointes.mp4",
  "repli-defensif-sprint": "/exercises/repli-defensif-sprint.mp4",
  "repositionnement-lateral-pas-chasses": "/exercises/repositionnement-lateral-pas-chasses.mp4",
  "respiration-retour-au-calme": "/exercises/respiration-retour-au-calme.mp4",
  "routine-penalty": "/exercises/routine-penalty.mp4",
  "sauts-a-la-corde": "/exercises/sauts-a-la-corde.mp4",
  "shuttle-run-match-simule": "/exercises/shuttle-run-match-simule.mp4",
  "skipping-genoux-hauts": "/exercises/skipping-genoux-hauts.mp4",
  "slalom-plots-serre": "/exercises/slalom-plots-serre.mp4",
  "sorties-aeriennes": "/exercises/sorties-aeriennes.mp4",
  "souleve-terre-jambe-tendue": "/exercises/souleve-terre-jambe-tendue.mp4",
  "sprint-changement-direction-5-10-5": "/exercises/sprint-changement-direction-5-10-5.mp4",
  "sprints-courts-10m": "/exercises/sprints-courts-10m.mp4",
  "squat-jumps": "/exercises/squat-jumps.mp4",
  "squats-bulgares": "/exercises/squats-bulgares.mp4",
  "squats-poids-du-corps": "/exercises/squats-poids-du-corps.mp4",
  "tacle-glisse-controle": "/exercises/tacle-glisse-controle.mp4",
  "talons-fesses": "/exercises/talons-fesses.mp4",
  "tete-plongeante-cage": "/exercises/tete-plongeante-cage.mp4",
  "tirage-elastique-dos": "/exercises/tirage-elastique-dos.mp4",
};
